version: "3.8"

services:
  proxy:
    container_name: proxy
    image: proxy
    build: nginx/.
    ports:
      - 80:80
  
  webserver:
    container_name: webserver
    image: opencve
    build: .
    depends_on:
      - postgres
    command: webserver -b 0.0.0.0:8000
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./conf/opencve.cfg:/app/opencve.cfg:ro

  celery_beat:
    container_name: celery_beat
    image: opencve
    depends_on:
      - webserver
      - redis
    command: celery-beat
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./conf/opencve.cfg:/app/opencve.cfg:ro

  celery_worker:
    container_name: celery_worker
    image: opencve
    depends_on:
      - webserver
      - redis
    command: celery-worker
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./conf/opencve.cfg:/app/opencve.cfg:ro

  redis:
    container_name: redis
    image: redis:buster
    networks:
      - backend
    ports:
      - 127.0.0.1:6379:6379
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: opencve
      POSTGRES_PASSWORD: opencve
      POSTGRES_DB: opencve
      PGDATA: /var/lib/postgreqsql/data
    networks:
      - backend
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgreqsql/data
    restart: unless-stopped

networks:
  backend:

volumes:
  postgres:
